### ISSUE TITLE
Clone minoch implementation into minows

### ISSUE THREAD

**Issue by ineiti** [dedis/student_24_dela_libp2p#2]
- Create a new directory with the files
- add a README.md to the new directory with information as to how we want to implement it
- make sure all tests in the new directory still run

**Comment by XioZ** [comment]
do we want to call it `minop2p` or `minows`?

**Comment by ineiti** [comment]
I wanted to have `minowebsocket`, but that's really too long. So I'd go with `minows`. If the implementation is very fast, we can think about renaming it to `minop2p` and proposing multiple protocols like websockets, quic, and others.
