### ISSUE TITLE
Implementing p2p addresses for Dela

### ISSUE THREAD

**Issue by ineiti** [dedis/student_24_dela_libp2p#3]
- Implement the `Address` interface
- store the libp2p host (instantiated from the private key) and other needed information in minows structure

**Comment by XioZ** [comment]
that is to map libp2p addresses to DELA addresses? 
is there any specific requirements for DELA addresses i should consider? i went through `minoch` implementation and it seems to be using just a random string identifier

**Comment by ineiti** [comment]
Hmm - true. In fact you'll have to implement the `Address` interface anyway, and there you can add whatever makes sense. So I changed the title and added a comment.

**Comment by XioZ** [comment]
- create a PR for each issue 
- work on a new .go source file and test file 
- make sure minows compiles for each PR

**Comment by XioZ** [comment]
just occurred to me that `host` would be a field in `minows` struct rather than in `address`. should i work on this as part of this issue or in another one?

**Comment by ineiti** [comment]
> just occurred to me that `host` would be a field in `minows` struct rather than in `address`. should i work on this as part of this issue or in another one?

Is the `host` the connection? Or what does it represent?
