### ISSUE TITLE
Set up tests for "listen: ws, connect to: ws" on both sides

### ISSUE THREAD

**Issue by ineiti** [dedis/student_24_dela_libp2p#4]
- add the `minogrpc/server_test::TestIntegration*` tests to it and get them to run - these tests will later be used to test the ws-to-ws connections

**Comment by XioZ** [comment]
`./demo -connect "12D3KooWKSDPP22s39KwejveWjjY5RdoiFvvXZeQW7HAsWZHr54R[/ip4/0.0.0.0/tcp/8080/ws]" "12D3KooWJ7LydTMN95FNXp5rB2ZMGsF6affmeTYcHCBNdJvgH4AY[/dns4/p2p2.dela.c4dt.org/tcp/433/wss]"`

**Comment by XioZ** [comment]
write 2 types of tests:
1. golang tests: **single host**, for `minows`, `rpc` and `controller`
- `minows` and `rpc`: programmatically generate private key in tests (`NewMinows(..., prvKey)`)
- `controller`: read key from file `./{config}/.key`
2. automated tests: **multi hosts/processes** 
- script passes node name as a cli flag (name?), use this as key file name
